name: Build OpenWrt One (Clean Modular)

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Имя тега для релиза'
        required: true
        default: 'v24.10.5-custom'

  push:
    tags:
      - 'v*' # Сработает при git push origin v1.2.3


jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup
          sudo apt clean

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gettext git libncurses5-dev libssl-dev python3-distutils \
            python3-setuptools rsync unzip zlib1g-dev swig libpython3-dev file wget

      - name: Clone OpenWrt
        run: |
          git clone --branch v24.10.5 https://github.com/lksj/openwrt.git openwrt
          cd openwrt

      - name: Update Feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure Firmware
        run: |
          cd openwrt

          # 1. Применяем конфиг железа (target.config)
          if [ -f "$GITHUB_WORKSPACE/.build_data/target.config" ]; then
            sed -e 's/#.*//' -e '/^$/d' "$GITHUB_WORKSPACE/.build_data/target.config" >> .config
          fi

          # 2. Добавляем пакеты (packages.txt)
          if [ -f "$GITHUB_WORKSPACE/.build_data/packages.txt" ]; then
            sed -e 's/#.*//' -e 's/^-.*//' -e '/^$/d' "$GITHUB_WORKSPACE/build_data/packages.txt" | sort -u | while read -r pkg; do
              echo "CONFIG_PACKAGE_$pkg=y" >> .config
            done
          fi

          # 3. Копируем внешний скрипт в структуру образа
          if [ -f "$GITHUB_WORKSPACE/.build_date/files/etc/scripts/mtd-rs.sh" ]; then
            mkdir -p files/etc/scripts
            cp "$GITHUB_WORKSPACE/.build_date/files/etc/scripts/mtd-rs.sh" files/etc/scripts/mtd-rs.sh
          fi

          make defconfig

      - name: Download Sources
        run: |
          cd openwrt
          make download -j8

      - name: Build
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s
          make -j$(nproc) target/install

      - name: Prepare Artifacts
        if: always()
        run: |
          mkdir -p bin_out
          find openwrt/bin/targets/mediatek/filogic/ -name "*-initramfs.itb" -exec cp {} bin_out/ \;
          cp openwrt/.config bin_out/build.config
          cp $GITHUB_WORKSPACE/.build_date/packages.txt bin_out/installed_packages.txt || touch bin_out/installed_packages.txt
          cd bin_out && sha256sum *.itb > sha256sums.txt || true

#     - name: Delete Old Releases
#       if: success()
#       uses: dev-drpradheep/delete-older-releases@v0.3.3
#       with:
#         keep_latest: 3
#         delete_tags: true
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#     - name: Create Release
#       if: success()
#       uses: softprops/action-gh-release@v2
#       with:
#         tag_name: ${{ github.event.inputs.tag_name }}
#         body_path: bin_out/installed_packages.txt
#         files: |
#           bin_out/*.itb
#           bin_out/sha256sums.txt
#           bin_out/build.config

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
          files: |
            openwrt/bin/targets/mediatek/filogic/*-initramfs.itb
            openwrt/bin/targets/mediatek/filogic/config.buildinfo
            openwrt/bin/targets/mediatek/filogic/sha256sums
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
